01-FrontEnd/Controllers/HobbyController.cs
using Common;
using Model.Domain;
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    public class HobbyController : Controller
    {
        private readonly IHobbyService _hobbyService = DependecyFactory.GetInstance<IHobbyService>();
        // GET: Hobby
        public ActionResult Index()
        {
            return View(
                    _hobbyService.GetAll()
                );
        }

        public ActionResult New() {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Hobby model)
        {
            _hobbyService.Insert(model);
            return RedirectToAction("Index");
        }

        public ActionResult Deleted(int id)
        {
            _hobbyService.Deleted(id);
            return  RedirectToAction("Index");
        }
    }
}

01-FrontEnd/Views/Hobby/Index.cshtml
@model IEnumerable<Hobby>
@{
    ViewBag.Title = "Index";
}

<h2 class="page-header">Hobby</h2>
<div class="btn-group btn-group-justified well">
    <a class="btn btn-danger" href="~/hobby/new">
        <i class="fa fa-plus"></i> Nuevo registro
    </a>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th style="width:40px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
            <tr>
                <td>
                  @m.Name
                </td>
                <td>
                    <a class="btn btn-xs btn-danger btn-block" href="~/hobby/deleted/@m.Id">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

01-FrontEnd/Views/Hobby/New.cshtml
@model Hobby

@{
    ViewBag.Title = "New";
}

<h2>New</h2>
@using (@Html.BeginForm("Create", "Hobby", FormMethod.Post)) {

    <div class="form-group">
        <label>Nombre</label>
        @Html.TextBoxFor(x => x.Name)
    </div>

    <button class="btn btn-success" type="submit">Save</button>


}